{{- if .Values.chat.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuroface.fullname" . }}-chat-token
  labels:
    {{- include "neuroface.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "neuroface.fullname" . }}-chat
type: kubernetes.io/service-account-token
{{- end }}
