apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neuroface.fullname" . }}-config
  labels:
    {{- include "neuroface.labels" . | nindent 4 }}
data:
  NEUROFACE_AI_MODEL: {{ .Values.backend.aiModel | quote }}
  NEUROFACE_DATA_DIR: "/data"
