apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuroface.fullname" . }}-frontend
  labels:
    {{- include "neuroface.frontendLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "neuroface.fullname" . }}-frontend
