{{- if and .Values.ovms.enabled .Values.ovms.externalUrl .Values.ovms.modelmesh.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-config
  labels:
    {{- include "neuroface.labels" . | nindent 4 }}
stringData:
  {{ include "neuroface.fullname" . }}-models: |
    {
      "type": "pvc",
      "name": "{{ include "neuroface.fullname" . }}-models"
    }
{{- end }}
