{{- if and .Values.ovms.enabled .Values.ovms.externalUrl .Values.ovms.modelmesh.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "neuroface.fullname" . }}-models
  labels:
    {{- include "neuroface.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ovms.modelmesh.storage.size | default "2Gi" }}
  {{- if .Values.ovms.modelmesh.storage.storageClassName }}
  storageClassName: {{ .Values.ovms.modelmesh.storage.storageClassName }}
  {{- end }}
{{- end }}
