title: NeuroFace
description: Facial Recognition & Object Detection — Powered by OpenShift & OpenShift AI

exclude:
  - "*.tgz"
  - index.yaml
  - artifacthub-repo.yml
  - favicon_2.ico
  - favicon_3.ico
  - favicon_4.ico
